"""
Seed catalogue.

Each tool is a dict:
- name    -> display name
- domain  -> fallback link + logo lookup
- free    -> True if there's a usable free plan (not just a trial)
- icon    -> Simple Icons slug for the real brand logo. "" = fall back.
- use     -> one short line: what you'd actually use it for
- href    -> optional deep link (program/application page). Public URLs only —
             never workspace pages or links with auth/tracking IDs.
- oss     -> optional True when the tool itself is open source / open weights
- alts    -> optional list of open-source alternatives: (name, domain, note)

Order inside each category is free-first.
"""

CATALOG = [
    {
        "slug": "assistants",
        "name": "Assistants",
        "lad": "As",
        "kind": "Ask anything, get answers",
        "tools": [
            {"name": "ChatGPT", "domain": "chatgpt.com", "free": True, "icon": "", "use": "Creativity, writing, everyday help", "offer": "ChatGPT Go free for 12 months with Airtel",
             "alts": [("Open WebUI", "openwebui.com", "Self-hosted chat UI"), ("LibreChat", "librechat.ai", "Multi-model chat"), ("Jan", "jan.ai", "Offline desktop AI")]},
            {"name": "Claude", "domain": "claude.ai", "free": True, "icon": "claude", "use": "Complex coding, deep reasoning",
             "alts": [("LibreChat", "librechat.ai", "Multi-model chat"), ("Open WebUI", "openwebui.com", "Self-hosted chat UI")]},
            {"name": "Gemini", "domain": "gemini.google.com", "free": True, "icon": "googlegemini", "use": "Images, multimodal, huge context", "offer": "Google AI Pro free 18 months with Jio 5G (₹349+ plan)",
             "alts": [("Open WebUI", "openwebui.com", "Self-hosted chat UI"), ("LibreChat", "librechat.ai", "Multi-model chat")]},
            {"name": "DeepSeek", "domain": "deepseek.com", "free": True, "icon": "deepseek", "use": "Math + reasoning, open weights", "repo": "https://github.com/deepseek-ai", "oss": True},
            {"name": "Perplexity", "domain": "perplexity.ai", "free": True, "icon": "perplexity", "use": "Research with citations", "offer": "Pro free for 12 months with Airtel",
             "alts": [("Perplexica", "github.com", "Open AI search engine"), ("SearXNG", "docs.searxng.org", "Private meta-search", "searxng")]},
            {"name": "Grok", "domain": "grok.com", "free": True, "icon": "", "use": "Real-time X knowledge"},
            {"name": "Mistral", "domain": "mistral.ai", "free": True, "icon": "mistralai", "use": "Open European models", "repo": "https://github.com/mistralai", "oss": True},
            {"name": "Ollama", "domain": "ollama.com", "free": True, "icon": "ollama", "use": "Run AI models locally", "repo": "https://github.com/ollama/ollama", "oss": True},
        ],
    },
    {
        "slug": "coding",
        "name": "Coding",
        "lad": "Co",
        "kind": "Write and fix code",
        "tools": [
            {"name": "Cline", "domain": "cline.bot", "free": True, "icon": "", "use": "Open-source agent in VS Code", "repo": "https://github.com/cline/cline", "oss": True},
            {"name": "Copilot", "domain": "github.com", "free": True, "icon": "githubcopilot", "use": "Autocomplete in your editor",
             "alts": [("Continue", "continue.dev", "Open IDE copilot"), ("Cline", "cline.bot", "Agent in VS Code", "cline"), ("Aider", "aider.chat", "Terminal pair programmer")]},
            {"name": "Bolt", "domain": "bolt.new", "free": True, "icon": "", "use": "Full apps in the browser",
             "alts": [("bolt.diy", "bolt.diy", "Bolt's own open build"), ("OpenHands", "all-hands.dev", "Autonomous dev agent")]},
            {"name": "Lovable", "domain": "lovable.dev", "free": True, "icon": "", "use": "Idea to web app",
             "alts": [("Dyad", "dyad.sh", "Local AI app builder"), ("bolt.diy", "bolt.diy", "Open in-browser builder")]},
            {"name": "v0", "domain": "v0.app", "free": True, "icon": "vercel", "use": "UI from a prompt",
             "alts": [("Onlook", "onlook.com", "Open design-to-code")]},
            {"name": "OpenCode", "domain": "opencode.ai", "free": True, "icon": "opencode", "use": "Open terminal coding agent", "repo": "https://github.com/sst/opencode", "oss": True},
            {"name": "Gemini CLI", "domain": "gemini.google.com", "free": True, "icon": "googlegemini", "use": "Google's terminal agent, free", "repo": "https://github.com/google-gemini/gemini-cli", "oss": True,
             "href": "https://github.com/google-gemini/gemini-cli"},
            {"name": "Codex CLI", "domain": "openai.com", "free": True, "icon": "", "use": "OpenAI's terminal agent", "repo": "https://github.com/openai/codex", "oss": True,
             "href": "https://github.com/openai/codex"},
            {"name": "Claude Code", "domain": "claude.com", "free": False, "icon": "claude", "use": "Terminal coding agent",
             "alts": [("OpenHands", "all-hands.dev", "Autonomous dev agent"), ("Aider", "aider.chat", "Terminal pair programmer"), ("Goose", "github.com", "Block's open agent")]},
        ],
    },
    {
        "slug": "ides",
        "name": "Agentic IDEs",
        "lad": "Ag",
        "kind": "Editors where AI agents do the work",
        "tools": [
            {"name": "Antigravity", "domain": "antigravity.google", "free": True, "icon": "", "use": "Google's agentic editor",
             "alts": [("Zed", "zed.dev", "Open editor, AI built in"), ("Cline", "cline.bot", "Agent in VS Code", "cline")]},
            {"name": "Cursor", "domain": "cursor.com", "free": True, "icon": "", "use": "AI-first code editor",
             "alts": [("Zed", "zed.dev", "Open editor, AI built in"), ("Continue", "continue.dev", "Open IDE copilot"), ("Cline", "cline.bot", "Agent in VS Code", "cline")]},
            {"name": "Windsurf", "domain": "windsurf.com", "free": True, "icon": "", "use": "Agentic code editor",
             "alts": [("Zed", "zed.dev", "Open editor, AI built in"), ("Continue", "continue.dev", "Open IDE copilot")]},
            {"name": "Kiro", "domain": "kiro.dev", "free": True, "icon": "", "use": "AWS spec-driven IDE"},
            {"name": "Trae", "domain": "trae.ai", "free": True, "icon": "trae", "use": "ByteDance's free AI IDE"},
            {"name": "Firebase Studio", "domain": "firebase.studio", "free": True, "icon": "firebase", "use": "Cloud IDE, app from a prompt"},
        ],
    },
    {
        "slug": "video",
        "name": "Video & image",
        "lad": "Vi",
        "kind": "Make pictures and videos",
        "tools": [
            {"name": "Krea", "domain": "krea.ai", "free": True, "icon": "", "use": "Real-time image playground",
             "alts": [("ComfyUI", "comfy.org", "Node-based SD and Flux"), ("Flux", "bfl.ai", "Open-weight image model")]},
            {"name": "Leonardo", "domain": "leonardo.ai", "free": True, "icon": "", "use": "Game art and illustrations",
             "alts": [("ComfyUI", "comfy.org", "Node-based SD and Flux"), ("Stable Diffusion", "stability.ai", "Open image models")]},
            {"name": "Kling", "domain": "klingai.com", "free": True, "icon": "", "use": "Text to video",
             "alts": [("Wan", "wan.video", "Alibaba's open video model"), ("HunyuanVideo", "hunyuan.tencent.com", "Tencent's open video model")]},
            {"name": "Freepik", "domain": "freepik.com", "free": True, "icon": "freepik", "use": "AI plus stock assets"},
            {"name": "ComfyUI", "domain": "comfy.org", "free": True, "icon": "", "use": "Node-based image + video studio", "repo": "https://github.com/comfyanonymous/ComfyUI", "oss": True},
            {"name": "SD WebUI", "domain": "github.com", "free": True, "icon": "", "use": "Classic image generation UI", "repo": "https://github.com/AUTOMATIC1111/stable-diffusion-webui", "oss": True,
             "href": "https://github.com/AUTOMATIC1111/stable-diffusion-webui"},
            {"name": "Pixabay", "domain": "pixabay.com", "free": True, "icon": "pixabay", "use": "Free stock photos + video"},
            {"name": "Seedance", "domain": "seed.bytedance.com", "free": True, "icon": "bytedance", "use": "ByteDance's video model",
             "href": "https://seed.bytedance.com/en/seedance"},
            {"name": "Runway", "domain": "runwayml.com", "free": False, "icon": "", "use": "Pro AI video editing",
             "alts": [("Wan", "wan.video", "Alibaba's open video model"), ("LTX-Video", "ltxv.video", "Fast open video model")]},
            {"name": "Flow", "domain": "labs.google", "free": False, "icon": "", "use": "Cinematic scenes by Google", "offer": "Part of Google AI Pro — free 18 months with Jio 5G",
             "alts": [("HunyuanVideo", "hunyuan.tencent.com", "Tencent's open video model")]},
            {"name": "Midjourney", "domain": "midjourney.com", "free": False, "icon": "", "use": "Best-in-class images",
             "alts": [("ComfyUI", "comfy.org", "Node-based SD and Flux"), ("Flux", "bfl.ai", "Open-weight image model"), ("Stable Diffusion", "stability.ai", "Open image models")]},
        ],
    },
    {
        "slug": "voice",
        "name": "Voice & audio",
        "lad": "Vo",
        "kind": "Make speech and music",
        "tools": [
            {"name": "Whisper", "domain": "openai.com", "free": True, "icon": "", "use": "Free speech to text", "repo": "https://github.com/openai/whisper", "oss": True,
             "href": "https://github.com/openai/whisper"},
            {"name": "ElevenLabs", "domain": "elevenlabs.io", "free": True, "icon": "elevenlabs", "use": "Lifelike text to speech",
             "alts": [("F5-TTS", "github.com", "Open voice cloning"), ("Piper", "github.com", "Fast local TTS"), ("OpenVoice", "github.com", "Instant voice clone")]},
            {"name": "Deepgram", "domain": "deepgram.com", "free": False, "icon": "", "use": "Fast transcription API",
             "alts": [("Whisper", "github.com", "OpenAI's open STT"), ("Vosk", "alphacephei.com", "Offline speech recognition")]},
            {"name": "Suno", "domain": "suno.com", "free": True, "icon": "", "use": "Full songs from a prompt",
             "alts": [("MusicGen", "audiocraft.metademolab.com", "Meta's open music model"), ("ACE-Step", "acestep.org", "Open music generation")]},
            {"name": "Murf", "domain": "murf.ai", "free": False, "icon": "", "use": "Voiceovers for videos",
             "alts": [("F5-TTS", "github.com", "Open voice cloning"), ("Piper", "github.com", "Fast local TTS")]},
            {"name": "Cartesia", "domain": "cartesia.ai", "free": True, "icon": "", "use": "Low-latency voice API",
             "alts": [("Piper", "github.com", "Fast local TTS")]},
        ],
    },
    {
        "slug": "identity",
        "name": "Identity & KYC",
        "lad": "KY",
        "kind": "Check someone is a real person",
        "tools": [
            {"name": "Didit", "domain": "didit.me", "free": True, "icon": "", "use": "Free ID verification"},
            {"name": "Persona", "domain": "withpersona.com", "free": False, "icon": "", "use": "KYC building blocks"},
            {"name": "HyperVerge", "domain": "hyperverge.co", "free": False, "icon": "", "use": "India-focused KYC"},
            {"name": "IDfy", "domain": "idfy.com", "free": False, "icon": "", "use": "Background checks, India"},
            {"name": "Signzy", "domain": "signzy.com", "free": False, "icon": "", "use": "Bank-grade onboarding"},
            {"name": "Sumsub", "domain": "sumsub.com", "free": False, "icon": "", "use": "Global KYC and AML"},
            {"name": "Onfido", "domain": "onfido.com", "free": False, "icon": "", "use": "Document + selfie checks"},
            {"name": "Veriff", "domain": "veriff.com", "free": False, "icon": "", "use": "Fast identity checks"},
        ],
    },
    {
        "slug": "otp",
        "name": "OTP & messaging",
        "lad": "OT",
        "kind": "Send OTP codes and SMS",
        "tools": [
            {"name": "Keycloak", "domain": "keycloak.org", "free": True, "icon": "keycloak", "use": "Self-hosted login + OTP", "repo": "https://github.com/keycloak/keycloak", "oss": True},
            {"name": "Firebase Auth", "domain": "firebase.google.com", "free": False, "icon": "firebase", "use": "Phone OTP login (SMS billed)",
             "alts": [("SuperTokens", "supertokens.com", "Open auth with OTP"), ("Keycloak", "keycloak.org", "Enterprise-grade SSO"), ("Ory", "ory.sh", "API-first open auth", "ory")]},
            {"name": "Fast2SMS", "domain": "fast2sms.com", "free": False, "icon": "", "use": "Cheap Indian SMS"},
            {"name": "2Factor", "domain": "2factor.in", "free": False, "icon": "", "use": "Indian OTP API"},
            {"name": "MSG91", "domain": "msg91.com", "free": False, "icon": "", "use": "OTP + WhatsApp, India"},
            {"name": "Plivo", "domain": "plivo.com", "free": False, "icon": "", "use": "Global SMS and voice"},
            {"name": "Twilio", "domain": "twilio.com", "free": False, "icon": "", "use": "The default SMS API"},
            {"name": "Vonage", "domain": "vonage.com", "free": False, "icon": "vonage", "use": "SMS and verify APIs"},
            {"name": "Infobip", "domain": "infobip.com", "free": False, "icon": "", "use": "Omnichannel messaging"},
        ],
    },
    {
        "slug": "payments",
        "name": "Payments",
        "lad": "Pa",
        "kind": "Get paid — even before you register a company",
        "tools": [
            {"name": "PhonePe PG", "domain": "phonepe.com", "free": True, "icon": "phonepe", "use": "Zero-fee UPI gateway",
             "href": "https://www.phonepe.com/business-solutions/payment-gateway/"},
            {"name": "Razorpay", "domain": "razorpay.com", "free": False, "icon": "razorpay", "use": "Indian payments, UPI + cards"},
            {"name": "Cashfree", "domain": "cashfree.com", "free": False, "icon": "", "use": "Gateway + instant payouts"},
            {"name": "Instamojo", "domain": "instamojo.com", "free": False, "icon": "", "use": "Payment links for individuals"},
            {"name": "Lemon Squeezy", "domain": "lemonsqueezy.com", "free": False, "icon": "lemonsqueezy", "use": "Sell globally, no company needed"},
            {"name": "Stripe", "domain": "stripe.com", "free": False, "icon": "stripe", "use": "Global cards + subscriptions"},
        ],
    },
    {
        "slug": "plugins",
        "name": "AI plugins",
        "lad": "AI",
        "kind": "Extend Claude, ChatGPT and agents",
        "tools": [
            {"name": "MCP Servers", "domain": "modelcontextprotocol.io", "free": True, "icon": "", "use": "The plugin standard for AI apps", "repo": "https://github.com/modelcontextprotocol/servers", "oss": True,
             "href": "https://github.com/modelcontextprotocol/servers"},
            {"name": "Smithery", "domain": "smithery.ai", "free": True, "icon": "", "use": "MCP server registry"},
            {"name": "Composio", "domain": "composio.dev", "free": True, "icon": "", "use": "250+ tool integrations"},
            {"name": "n8n", "domain": "n8n.io", "free": True, "icon": "n8n", "use": "Automation with AI nodes", "repo": "https://github.com/n8n-io/n8n", "oss": True},
            {"name": "Dify", "domain": "dify.ai", "free": True, "icon": "", "use": "Open LLM app platform", "repo": "https://github.com/langgenius/dify", "oss": True},
            {"name": "Flowise", "domain": "flowiseai.com", "free": True, "icon": "", "use": "Drag-drop agent builder", "repo": "https://github.com/FlowiseAI/Flowise", "oss": True},
            {"name": "Langflow", "domain": "langflow.org", "free": True, "icon": "langflow", "use": "Visual agent builder", "repo": "https://github.com/langflow-ai/langflow", "oss": True},
            {"name": "Activepieces", "domain": "activepieces.com", "free": True, "icon": "", "use": "Open Zapier alternative", "repo": "https://github.com/activepieces/activepieces", "oss": True},
            {"name": "OpenRouter", "domain": "openrouter.ai", "free": True, "icon": "", "use": "Every AI model, one API"},
        ],
    },
    {
        "slug": "ideas",
        "name": "Ideas",
        "lad": "Id",
        "kind": "Problems worth building — from real companies only",
        "tools": [
            {"name": "YC Requests", "domain": "ycombinator.com", "free": True, "icon": "ycombinator", "use": "Ideas YC wants built", "href": "https://www.ycombinator.com/rfs"},
            {"name": "Fix My Itch", "domain": "razorpay.com", "free": True, "icon": "razorpay", "use": "Real problems, India fintech", "href": "https://razorpay.com/m/fix-my-itch/"},
            {"name": "a16z Big Ideas", "domain": "a16z.com", "free": True, "icon": "", "use": "What a16z sees coming", "href": "https://a16z.com/big-ideas-in-tech-2025/"},
            {"name": "AI Grant", "domain": "aigrant.org", "free": True, "icon": "", "use": "Funded open AI ideas", "href": "https://aigrant.org/"},
            {"name": "Smart India Hackathon", "domain": "sih.gov.in", "free": True, "icon": "", "use": "Govt problem statements", "href": "https://www.sih.gov.in/"},
            {"name": "AIM Challenges", "domain": "aim.gov.in", "free": True, "icon": "", "use": "Atal innovation missions", "href": "https://aim.gov.in/"},
        ],
    },
    {
        "slug": "programs",
        "name": "Startup programs",
        "lad": "St",
        "kind": "Free credits and perks for founders",
        "tools": [
            {"name": "AWS Activate", "domain": "aws.amazon.com", "free": True, "icon": "", "use": "AWS cloud credits", "href": "https://aws.amazon.com/startups"},
            {"name": "Google for Startups", "domain": "cloud.google.com", "free": True, "icon": "googlecloud", "use": "GCP credits + Workspace", "href": "https://cloud.google.com/startup/apply"},
            {"name": "NVIDIA Inception", "domain": "nvidia.com", "free": True, "icon": "nvidia", "use": "Path to $100K AWS credits", "href": "https://www.nvidia.com/en-in/startups/"},
            {"name": "MongoDB for Startups", "domain": "mongodb.com", "free": True, "icon": "mongodb", "use": "Atlas credits + advisor", "href": "https://www.mongodb.com/startups"},
            {"name": "Claude for Startups", "domain": "anthropic.com", "free": True, "icon": "claude", "use": "Claude API credits", "href": "https://www.anthropic.com/startups"},
            {"name": "OpenAI Startups", "domain": "openai.com", "free": True, "icon": "", "use": "Builder community + credits", "href": "https://openai.com/startups"},
            {"name": "ElevenLabs Grants", "domain": "elevenlabs.io", "free": True, "icon": "elevenlabs", "use": "Voice API grant", "href": "https://elevenlabs.io/startup-grants"},
            {"name": "Sentry for Startups", "domain": "sentry.io", "free": True, "icon": "sentry", "use": "$5K monitoring credits", "href": "https://sentry.io/for/startups/"},
            {"name": "Cloudflare Startups", "domain": "cloudflare.com", "free": True, "icon": "cloudflare", "use": "Product credits", "href": "https://www.cloudflare.com/forstartups/"},
            {"name": "GitLab for Startups", "domain": "gitlab.com", "free": True, "icon": "gitlab", "use": "Free GitLab Ultimate", "href": "https://about.gitlab.com/solutions/startups/"},
            {"name": "Retool for Startups", "domain": "retool.com", "free": True, "icon": "", "use": "Internal-tool credits", "href": "https://retool.com/startups"},
            {"name": "Persona Startups", "domain": "withpersona.com", "free": True, "icon": "", "use": "KYC + KYB free tier", "href": "https://help.withpersona.com/articles/1XNnqukfZY9VamF2e7jkuJ/"},
            {"name": "Signzy Startups", "domain": "signzy.com", "free": True, "icon": "", "use": "KYC + KYB APIs, India", "href": "https://www.signzy.com/fintech-apis/startups"},
            {"name": "AssemblyAI Startups", "domain": "assemblyai.com", "free": True, "icon": "", "use": "Speech-to-text credits", "href": "https://www.assemblyai.com/contact/startup-program"},
            {"name": "Arize for Startups", "domain": "arize.com", "free": True, "icon": "", "use": "LLM observability + evals", "href": "https://arize.com/arize-for-startups/"},
            {"name": "Perplexity Startups", "domain": "perplexity.ai", "free": True, "icon": "perplexity", "use": "API credits + Pro", "href": "https://www.perplexity.ai/startups"},
            {"name": "DocSend Startups", "domain": "dropbox.com", "free": True, "icon": "dropbox", "use": "90% off deck sharing", "href": "https://experience.dropbox.com/docsend/startups"},
            {"name": "Infobip Tribe", "domain": "infobip.com", "free": True, "icon": "", "use": "Messaging credits", "href": "https://www.infobip.com/startup"},
            {"name": "Google Ads credit", "domain": "ads.google.com", "free": True, "icon": "googleads", "use": "Ad credit after first spend", "href": "https://ads.google.com/aw/signup"},
            {"name": "Stripe Atlas", "domain": "stripe.com", "free": False, "icon": "stripe", "use": "US inc + partner perks", "href": "https://stripe.com/atlas"},
            {"name": "Azure for Students", "domain": "azure.microsoft.com", "free": True, "icon": "", "use": "$100 Azure credit", "href": "https://azure.microsoft.com/free/students"},
        ],
    },
    {
        "slug": "stack",
        "name": "Builder stack",
        "lad": "Bu",
        "kind": "What we actually build with",
        "tools": [
            {"name": "GitHub", "domain": "github.com", "free": True, "icon": "github", "use": "Code hosting",
             "alts": [("Gitea", "about.gitea.com", "Lightweight self-host git", "gitea"), ("Forgejo", "forgejo.org", "Community Gitea fork", "forgejo"), ("GitLab CE", "gitlab.com", "Open-core DevOps", "gitlab")]},
            {"name": "Supabase", "domain": "supabase.com", "free": True, "icon": "supabase", "use": "Postgres backend", "repo": "https://github.com/supabase/supabase", "oss": True,
             "alts": [("Appwrite", "appwrite.io", "Open backend platform", "appwrite"), ("PocketBase", "pocketbase.io", "One-file backend", "pocketbase"), ("Nhost", "nhost.io", "GraphQL backend", "nhost")]},
            {"name": "Postman", "domain": "postman.com", "free": True, "icon": "postman", "use": "API testing",
             "alts": [("Bruno", "usebruno.com", "Offline API client", "bruno"), ("Hoppscotch", "hoppscotch.io", "Web API client", "hoppscotch")]},
            {"name": "Expo", "domain": "expo.dev", "free": True, "icon": "expo", "use": "React Native builds", "repo": "https://github.com/expo/expo", "oss": True},
            {"name": "Replit", "domain": "replit.com", "free": True, "icon": "replit", "use": "Cloud IDE + hosting",
             "alts": [("code-server", "coder.com", "VS Code in your browser", "coder"), ("DevPod", "devpod.sh", "Open dev environments")]},
            {"name": "Bubble", "domain": "bubble.io", "free": True, "icon": "", "use": "No-code web apps",
             "alts": [("Budibase", "budibase.com", "Open low-code apps", "budibase"), ("Appsmith", "appsmith.com", "Open internal tools", "appsmith"), ("ToolJet", "tooljet.com", "Open app builder")]},
            {"name": "PostHog", "domain": "posthog.com", "free": True, "icon": "posthog", "use": "Product analytics", "repo": "https://github.com/PostHog/posthog", "oss": True,
             "alts": [("Umami", "umami.is", "Simple web analytics", "umami"), ("Matomo", "matomo.org", "Full analytics suite", "matomo"), ("Plausible", "plausible.io", "Privacy-first analytics", "plausibleanalytics")]},
            {"name": "Resend", "domain": "resend.com", "free": True, "icon": "resend", "use": "Email API",
             "alts": [("Postal", "postalserver.io", "Self-hosted mail server"), ("Listmonk", "listmonk.app", "Newsletter + campaigns", "listmonk")]},
            {"name": "New Relic", "domain": "newrelic.com", "free": True, "icon": "newrelic", "use": "App monitoring",
             "alts": [("SigNoz", "signoz.io", "Open observability"), ("Grafana", "grafana.com", "Dashboards + traces", "grafana"), ("OpenObserve", "openobserve.ai", "Logs at 140x less cost")]},
            {"name": "CodeRabbit", "domain": "coderabbit.ai", "free": True, "icon": "", "use": "AI pull-request reviews",
             "alts": [("PR-Agent", "qodo.ai", "Qodo's open PR reviewer")]},
            {"name": "Notion", "domain": "notion.so", "free": True, "icon": "notion", "use": "Docs and wikis",
             "alts": [("AppFlowy", "appflowy.io", "Open Notion alternative"), ("AFFiNE", "affine.pro", "Docs + whiteboard", "affine"), ("Outline", "getoutline.com", "Team knowledge base")]},
            {"name": "Slack", "domain": "slack.com", "free": True, "icon": "", "use": "Team chat",
             "alts": [("Mattermost", "mattermost.com", "Self-hosted team chat", "mattermost"), ("Rocket.Chat", "rocket.chat", "Open team chat", "rocketdotchat"), ("Zulip", "zulip.com", "Threaded open chat", "zulip")]},
            {"name": "Whimsical", "domain": "whimsical.com", "free": True, "icon": "", "use": "Diagrams and wireframes",
             "alts": [("Excalidraw", "excalidraw.com", "Hand-drawn diagrams", "excalidraw"), ("draw.io", "drawio.com", "Classic diagramming", "diagramsdotnet")]},
            {"name": "Google AI Studio", "domain": "aistudio.google.com", "free": True, "icon": "", "use": "Gemini API playground",
             "alts": [("Open WebUI", "openwebui.com", "Self-hosted chat UI")]},
            {"name": "Otter", "domain": "otter.ai", "free": True, "icon": "", "use": "Meeting notes",
             "alts": [("Whisper", "github.com", "OpenAI's open STT")]},
            {"name": "Mercury", "domain": "mercury.com", "free": True, "icon": "", "use": "Startup banking"},
            {"name": "Coolify", "domain": "coolify.io", "free": True, "icon": "coolify", "use": "Self-host your apps", "repo": "https://github.com/coollabsio/coolify", "oss": True},
            {"name": "Uptime Kuma", "domain": "uptime.kuma.pet", "free": True, "icon": "uptimekuma", "use": "Is-my-site-up monitoring", "repo": "https://github.com/louislam/uptime-kuma", "oss": True},
            {"name": "NocoDB", "domain": "nocodb.com", "free": True, "icon": "", "use": "Open Airtable alternative", "repo": "https://github.com/nocodb/nocodb", "oss": True},
            {"name": "Strapi", "domain": "strapi.io", "free": True, "icon": "strapi", "use": "Headless CMS", "repo": "https://github.com/strapi/strapi", "oss": True},
            {"name": "Capacities", "domain": "capacities.io", "free": True, "icon": "", "use": "Notes as a knowledge graph",
             "href": "https://capacities.io/"},
            {"name": "Obsidian", "domain": "obsidian.md", "free": True, "icon": "obsidian", "use": "Local-first linked notes"},
            {"name": "LaunchDarkly", "domain": "launchdarkly.com", "free": True, "icon": "", "use": "Feature flags",
             "alts": [("Unleash", "getunleash.io", "Open feature flags"), ("Flagsmith", "flagsmith.com", "Flags + remote config"), ("GrowthBook", "growthbook.io", "Flags + A/B tests")]},
        ],
    },
]


# One plain-English sentence per product — shown in the info popup.
DESCS = {
    'ChatGPT': 'The most popular AI chatbot — ask it anything, it writes, plans and explains.',
    'Claude': 'AI assistant that is best-in-class at writing code and thinking through hard problems.',
    'Gemini': "Google's AI — makes images, reads long files, works inside Gmail and Docs.",
    'DeepSeek': 'Free Chinese AI that rivals the paid ones at math and logic.',
    'Perplexity': 'A search engine that answers in sentences and shows its sources.',
    'Grok': "X's AI — knows what's happening on the internet right now.",
    'Mistral': 'French AI lab — fast models you can also download and run yourself.',
    'Cline': 'Free VS Code extension that writes and edits code for you like an employee.',
    'Copilot': "GitHub's AI that finishes your code as you type.",
    'Windsurf': 'A code editor where AI does multi-step tasks across your whole project.',
    'Cursor': 'The most popular AI code editor — chat with your codebase.',
    'Bolt': 'Type an idea, get a working web app in your browser.',
    'Lovable': 'Describe an app in plain English and it builds and hosts it.',
    'v0': "Vercel's tool — describe a screen, get real working UI code.",
    'Claude Code': 'Claude in your terminal — it edits files, runs commands and ships features.',
    'Krea': 'Draw rough shapes and watch AI turn them into polished images live.',
    'Leonardo': 'Make game art, characters and illustrations from text.',
    'Kling': 'Turn a sentence or a photo into a short video clip.',
    'Freepik': 'Stock photos and icons plus AI image tools in one place.',
    'Runway': 'Hollywood-grade AI video editing — remove objects, generate scenes.',
    'Flow': "Google's AI filmmaking tool for cinematic clips.",
    'Midjourney': 'The gold standard for beautiful AI images.',
    'ElevenLabs': 'Turns text into voices that sound completely human.',
    'Deepgram': 'Converts speech to text fast — built for apps and call centers.',
    'Suno': 'Type a vibe, get a full song with vocals.',
    'Murf': 'Studio-quality voiceovers for videos and ads.',
    'Cartesia': 'Instant, natural AI voices for real-time apps like phone agents.',
    'Didit': 'Checks government IDs and faces — the core checks are free forever.',
    'Persona': 'Building blocks to verify who your users are, used by big startups.',
    'HyperVerge': 'ID checks tuned for Indian documents like Aadhaar and PAN.',
    'IDfy': 'Background checks and document verification for Indian businesses.',
    'Signzy': 'Bank-grade customer onboarding used by Indian banks.',
    'Sumsub': 'One dashboard to verify users in any country.',
    'Onfido': 'Match a selfie to an ID document in seconds.',
    'Veriff': 'Fast video-based identity checks.',
    'Firebase Auth': "Google's login system — phone OTP, email, social logins (SMS costs extra).",
    'Fast2SMS': 'Send SMS in India at rock-bottom prices.',
    '2Factor': 'Simple Indian API for OTP codes over SMS.',
    'MSG91': 'OTP, SMS and WhatsApp messages for Indian businesses.',
    'Plivo': 'Send SMS and make calls worldwide from code.',
    'Twilio': "The world's default for sending SMS from an app.",
    'Vonage': 'SMS, calls and verification APIs.',
    'Infobip': 'One API for SMS, WhatsApp, email and more.',
    'MCP Servers': 'The open standard that lets AI apps like Claude plug into your tools.',
    'Smithery': 'An app store of ready-made MCP plugins for AI assistants.',
    'Composio': 'Connect your AI agent to Gmail, Slack, Notion — 250+ apps.',
    'n8n': 'Drag-and-drop automation you can self-host — Zapier, but open source.',
    'Dify': 'Build AI apps and chatbots visually — open source.',
    'Flowise': 'Drag boxes, connect arrows, get an AI agent — open source.',
    'YC Requests': "Y Combinator's official list of startups they wish existed.",
    'Fix My Itch': "Razorpay's list of real problems Indian founders should solve.",
    'a16z Big Ideas': "What one of the world's top VC firms thinks is coming next.",
    'AI Grant': 'Nat Friedman and Daniel Gross fund these open AI ideas.',
    'Smart India Hackathon': 'Real problem statements from Indian government ministries.',
    'AIM Challenges': "Atal Innovation Mission's national innovation challenges.",
    'AWS Activate': 'Free AWS cloud credits for startups — up to $100K.',
    'Google for Startups': 'Free Google Cloud credits plus Workspace for young startups.',
    'NVIDIA Inception': "NVIDIA's startup club — GPU perks, training and partner credits.",
    'MongoDB for Startups': 'Free database credits plus a technical advisor.',
    'Claude for Startups': 'Free Claude API credits for building AI products.',
    'OpenAI Startups': "OpenAI's community and credits for startup builders.",
    'ElevenLabs Grants': 'Free voice AI credits for early-stage startups.',
    'Sentry for Startups': '$5,000 of error-tracking credits, free.',
    'Cloudflare Startups': "Free credits across Cloudflare's whole product line.",
    'GitLab for Startups': "GitLab's top plan free for qualifying startups.",
    'Retool for Startups': 'Credits to build internal dashboards fast.',
    'Persona Startups': 'Free identity-verification tier for startups.',
    'Signzy Startups': 'Startup pricing for India-grade KYC and KYB APIs.',
    'AssemblyAI Startups': 'Free speech-to-text credits for voice startups.',
    'Arize for Startups': "Free tools to catch your AI agent's mistakes before users do.",
    'Perplexity Startups': 'API credits and Pro seats for startups.',
    'DocSend Startups': '90% off the tool investors expect your pitch deck on.',
    'Infobip Tribe': 'Free messaging credits for startups.',
    'Google Ads credit': 'Spend a little on ads, Google matches it with credit.',
    'Stripe Atlas': 'Incorporate a US company from anywhere — $500, includes perks.',
    'Azure for Students': '$100 of Microsoft cloud free with a student email.',
    'GitHub': 'Where the world stores its code.',
    'Supabase': 'A complete backend — database, login, storage — from one dashboard.',
    'Postman': 'Test your APIs by clicking instead of coding.',
    'Expo': 'Build iPhone and Android apps with one codebase.',
    'Replit': 'Code, run and host projects entirely in the browser.',
    'Bubble': 'Build real web apps by dragging and dropping — no code.',
    'PostHog': 'See what users actually do inside your product.',
    'Resend': 'Send emails from your app with three lines of code.',
    'New Relic': "Watch your app's health — errors, speed, crashes.",
    'CodeRabbit': 'AI that reviews your pull requests before humans do.',
    'Notion': 'Docs, wikis and databases in one workspace.',
    'Slack': 'Where teams chat.',
    'Whimsical': 'Quick flowcharts, wireframes and mind maps.',
    'Google AI Studio': "Try Google's Gemini models free and grab an API key.",
    'Otter': 'Records meetings and writes the notes for you.',
    'Mercury': 'A bank account built for startups — no fees.',
    'LaunchDarkly': 'Turn features on and off without redeploying.',
    'Razorpay': 'How Indian startups accept payments — signs up unregistered individuals and freelancers too.',
    'PhonePe PG': 'Accept UPI payments with zero transaction fees — free for any business size.',
    'Cashfree': 'Indian payment gateway known for instant settlements and easy onboarding.',
    'Instamojo': 'Share a payment link and get paid — built for individuals, no company registration needed.',
    'Lemon Squeezy': 'Sell software worldwide without registering a company — they handle taxes as the merchant.',
    'Stripe': 'The global standard for accepting cards and subscriptions online.',
    'Ollama': 'One command to run ChatGPT-style models on your own computer, free.',
    'OpenCode': 'Open-source coding agent that lives in your terminal — free Claude Code alternative.',
    'Gemini CLI': "Google's free coding agent for your terminal — open source.",
    'Codex CLI': "OpenAI's coding agent for your terminal — open source.",
    'ComfyUI': 'Free visual studio where you wire boxes together to make images and videos.',
    'SD WebUI': 'The classic free tool that started home AI image generation.',
    'Whisper': "OpenAI's free model that turns any recording into accurate text.",
    'Keycloak': 'Run your own login system — passwords, OTP, SSO — free forever.',
    'Langflow': 'Drag and drop boxes to build AI agents without writing code.',
    'Activepieces': 'Connect your apps and add AI steps — an open-source Zapier.',
    'Coolify': 'Deploy your apps on your own server with one click — a free Heroku.',
    'Uptime Kuma': 'A pretty dashboard that pings your site and alerts you when it goes down.',
    'NocoDB': 'Turns any database into a friendly Airtable-style spreadsheet.',
    'Strapi': "Manage your website's content from a clean admin panel — open source.",
    'OpenRouter': 'One API key that talks to ChatGPT, Claude, Gemini and 400+ models — some free.',
    'Pixabay': 'Millions of free stock photos, videos and music — no attribution needed.',
    'Seedance': "ByteDance's top-ranked video model — try it free inside Dreamina or BytePlus.",
    'Capacities': 'A notebook where every note becomes a connected object — what we use for notes daily.',
    'Obsidian': 'Markdown notes stored on your own device, linked like a second brain — free for personal use.',
    'Antigravity': "Google's free agentic editor — Gemini agents plan, write and verify code across editor, terminal and browser.",
    'Kiro': "AWS's agentic IDE — describe the spec, agents build and keep the code true to it.",
    'Trae': "ByteDance's AI IDE with a full agent mode built in — generous free tier.",
    'Firebase Studio': "Google's free cloud IDE — describe an app and agents scaffold, build and deploy it.",
}
