"""
Seed catalogue.

Each tool is a dict:
- name    -> display name
- domain  -> fallback link + logo lookup
- free    -> True if there's a usable free plan (not just a trial)
- icon    -> Simple Icons slug for the real brand logo. "" = fall back.
- use     -> one short line: what you'd actually use it for
- href    -> optional deep link (program/application page). Public URLs only —
             never workspace pages or links with auth/tracking IDs.
- oss     -> optional True when the tool itself is open source / open weights
- alts    -> optional list of open-source alternatives: (name, domain, note)

Order inside each category is free-first.
"""

CATALOG = [
    {
        "slug": "assistants",
        "name": "Assistants",
        "kind": "Ask anything, get answers",
        "tools": [
            {"name": "ChatGPT", "domain": "chatgpt.com", "free": True, "icon": "openai", "use": "Creativity, writing, everyday help",
             "alts": [("Open WebUI", "openwebui.com", "Self-hosted chat UI"), ("LibreChat", "librechat.ai", "Multi-model chat"), ("Jan", "jan.ai", "Offline desktop AI")]},
            {"name": "Claude", "domain": "claude.ai", "free": True, "icon": "claude", "use": "Complex coding, deep reasoning",
             "alts": [("LibreChat", "librechat.ai", "Multi-model chat"), ("Open WebUI", "openwebui.com", "Self-hosted chat UI")]},
            {"name": "Gemini", "domain": "gemini.google.com", "free": True, "icon": "googlegemini", "use": "Images, multimodal, huge context",
             "alts": [("Open WebUI", "openwebui.com", "Self-hosted chat UI"), ("LibreChat", "librechat.ai", "Multi-model chat")]},
            {"name": "DeepSeek", "domain": "deepseek.com", "free": True, "icon": "deepseek", "use": "Math + reasoning, open weights", "oss": True},
            {"name": "Perplexity", "domain": "perplexity.ai", "free": True, "icon": "perplexity", "use": "Research with citations",
             "alts": [("Perplexica", "github.com", "Open AI search engine"), ("SearXNG", "docs.searxng.org", "Private meta-search")]},
            {"name": "Grok", "domain": "grok.com", "free": True, "icon": "grok", "use": "Real-time X knowledge"},
            {"name": "Mistral", "domain": "mistral.ai", "free": True, "icon": "mistralai", "use": "Open European models", "oss": True},
        ],
    },
    {
        "slug": "coding",
        "name": "Coding",
        "kind": "Write and fix code",
        "tools": [
            {"name": "Cline", "domain": "cline.bot", "free": True, "icon": "", "use": "Open-source agent in VS Code", "oss": True},
            {"name": "Copilot", "domain": "github.com", "free": True, "icon": "githubcopilot", "use": "Autocomplete in your editor",
             "alts": [("Continue", "continue.dev", "Open IDE copilot"), ("Cline", "cline.bot", "Agent in VS Code"), ("Aider", "aider.chat", "Terminal pair programmer")]},
            {"name": "Windsurf", "domain": "windsurf.com", "free": True, "icon": "", "use": "Agentic code editor",
             "alts": [("Zed", "zed.dev", "Open editor, AI built in"), ("Continue", "continue.dev", "Open IDE copilot")]},
            {"name": "Cursor", "domain": "cursor.com", "free": True, "icon": "", "use": "AI-first code editor",
             "alts": [("Zed", "zed.dev", "Open editor, AI built in"), ("Continue", "continue.dev", "Open IDE copilot"), ("Cline", "cline.bot", "Agent in VS Code")]},
            {"name": "Bolt", "domain": "bolt.new", "free": True, "icon": "", "use": "Full apps in the browser",
             "alts": [("bolt.diy", "github.com", "Bolt's own open build"), ("OpenHands", "all-hands.dev", "Autonomous dev agent")]},
            {"name": "Lovable", "domain": "lovable.dev", "free": True, "icon": "", "use": "Idea to web app",
             "alts": [("Dyad", "dyad.sh", "Local AI app builder"), ("bolt.diy", "github.com", "Open in-browser builder")]},
            {"name": "v0", "domain": "v0.app", "free": True, "icon": "vercel", "use": "UI from a prompt",
             "alts": [("Onlook", "onlook.com", "Open design-to-code")]},
            {"name": "Claude Code", "domain": "claude.com", "free": False, "icon": "claude", "use": "Terminal coding agent",
             "alts": [("OpenHands", "all-hands.dev", "Autonomous dev agent"), ("Aider", "aider.chat", "Terminal pair programmer"), ("Goose", "github.com", "Block's open agent")]},
        ],
    },
    {
        "slug": "video",
        "name": "Video & image",
        "kind": "Make pictures and videos",
        "tools": [
            {"name": "Krea", "domain": "krea.ai", "free": True, "icon": "", "use": "Real-time image playground",
             "alts": [("ComfyUI", "comfy.org", "Node-based SD and Flux"), ("Flux", "bfl.ai", "Open-weight image model")]},
            {"name": "Leonardo", "domain": "leonardo.ai", "free": True, "icon": "", "use": "Game art and illustrations",
             "alts": [("ComfyUI", "comfy.org", "Node-based SD and Flux"), ("Stable Diffusion", "stability.ai", "Open image models")]},
            {"name": "Kling", "domain": "klingai.com", "free": True, "icon": "", "use": "Text to video",
             "alts": [("Wan", "github.com", "Alibaba's open video model"), ("HunyuanVideo", "hunyuan.tencent.com", "Tencent's open video model")]},
            {"name": "Freepik", "domain": "freepik.com", "free": True, "icon": "freepik", "use": "AI plus stock assets"},
            {"name": "Runway", "domain": "runwayml.com", "free": False, "icon": "", "use": "Pro AI video editing",
             "alts": [("Wan", "github.com", "Alibaba's open video model"), ("LTX-Video", "github.com", "Fast open video model")]},
            {"name": "Flow", "domain": "labs.google", "free": False, "icon": "", "use": "Cinematic scenes by Google",
             "alts": [("HunyuanVideo", "hunyuan.tencent.com", "Tencent's open video model")]},
            {"name": "Midjourney", "domain": "midjourney.com", "free": False, "icon": "midjourney", "use": "Best-in-class images",
             "alts": [("ComfyUI", "comfy.org", "Node-based SD and Flux"), ("Flux", "bfl.ai", "Open-weight image model"), ("Stable Diffusion", "stability.ai", "Open image models")]},
        ],
    },
    {
        "slug": "voice",
        "name": "Voice & audio",
        "kind": "Make speech and music",
        "tools": [
            {"name": "ElevenLabs", "domain": "elevenlabs.io", "free": True, "icon": "elevenlabs", "use": "Lifelike text to speech",
             "alts": [("Coqui XTTS", "github.com", "Voice-cloning TTS"), ("Piper", "github.com", "Fast local TTS"), ("OpenVoice", "github.com", "Instant voice clone")]},
            {"name": "Deepgram", "domain": "deepgram.com", "free": False, "icon": "", "use": "Fast transcription API",
             "alts": [("Whisper", "github.com", "OpenAI's open STT"), ("Vosk", "alphacephei.com", "Offline speech recognition")]},
            {"name": "Suno", "domain": "suno.com", "free": True, "icon": "", "use": "Full songs from a prompt",
             "alts": [("MusicGen", "github.com", "Meta's open music model"), ("ACE-Step", "github.com", "Open music generation")]},
            {"name": "Murf", "domain": "murf.ai", "free": False, "icon": "", "use": "Voiceovers for videos",
             "alts": [("Coqui XTTS", "github.com", "Voice-cloning TTS"), ("Piper", "github.com", "Fast local TTS")]},
            {"name": "Cartesia", "domain": "cartesia.ai", "free": True, "icon": "", "use": "Low-latency voice API",
             "alts": [("Piper", "github.com", "Fast local TTS")]},
            {"name": "PlayHT", "domain": "play.ht", "free": True, "icon": "", "use": "Voice cloning",
             "alts": [("OpenVoice", "github.com", "Instant voice clone"), ("Coqui XTTS", "github.com", "Voice-cloning TTS")]},
        ],
    },
    {
        "slug": "identity",
        "name": "Identity & KYC",
        "kind": "Check someone is a real person",
        "tools": [
            {"name": "Didit", "domain": "didit.me", "free": True, "icon": "", "use": "Free ID verification"},
            {"name": "Persona", "domain": "withpersona.com", "free": False, "icon": "", "use": "KYC building blocks"},
            {"name": "HyperVerge", "domain": "hyperverge.co", "free": False, "icon": "", "use": "India-focused KYC"},
            {"name": "IDfy", "domain": "idfy.com", "free": False, "icon": "", "use": "Background checks, India"},
            {"name": "Signzy", "domain": "signzy.com", "free": False, "icon": "", "use": "Bank-grade onboarding"},
            {"name": "Sumsub", "domain": "sumsub.com", "free": False, "icon": "", "use": "Global KYC and AML"},
            {"name": "Onfido", "domain": "onfido.com", "free": False, "icon": "", "use": "Document + selfie checks"},
            {"name": "Veriff", "domain": "veriff.com", "free": False, "icon": "", "use": "Fast identity checks"},
        ],
    },
    {
        "slug": "otp",
        "name": "OTP & messaging",
        "kind": "Send OTP codes and SMS",
        "tools": [
            {"name": "Firebase Auth", "domain": "firebase.google.com", "free": False, "icon": "firebase", "use": "Phone OTP login (SMS billed)",
             "alts": [("SuperTokens", "supertokens.com", "Open auth with OTP"), ("Keycloak", "keycloak.org", "Enterprise-grade SSO"), ("Ory", "ory.sh", "API-first open auth")]},
            {"name": "Fast2SMS", "domain": "fast2sms.com", "free": False, "icon": "", "use": "Cheap Indian SMS"},
            {"name": "2Factor", "domain": "2factor.in", "free": False, "icon": "", "use": "Indian OTP API"},
            {"name": "MSG91", "domain": "msg91.com", "free": False, "icon": "", "use": "OTP + WhatsApp, India"},
            {"name": "Plivo", "domain": "plivo.com", "free": False, "icon": "", "use": "Global SMS and voice"},
            {"name": "Twilio", "domain": "twilio.com", "free": False, "icon": "twilio", "use": "The default SMS API"},
            {"name": "Vonage", "domain": "vonage.com", "free": False, "icon": "vonage", "use": "SMS and verify APIs"},
            {"name": "Infobip", "domain": "infobip.com", "free": False, "icon": "infobip", "use": "Omnichannel messaging"},
        ],
    },
    {
        "slug": "plugins",
        "name": "AI plugins",
        "kind": "Extend Claude, ChatGPT and agents",
        "tools": [
            {"name": "MCP Servers", "domain": "modelcontextprotocol.io", "free": True, "icon": "", "use": "The plugin standard for AI apps", "oss": True,
             "href": "https://github.com/modelcontextprotocol/servers"},
            {"name": "Smithery", "domain": "smithery.ai", "free": True, "icon": "", "use": "MCP server registry"},
            {"name": "Composio", "domain": "composio.dev", "free": True, "icon": "", "use": "250+ tool integrations"},
            {"name": "n8n", "domain": "n8n.io", "free": True, "icon": "n8n", "use": "Automation with AI nodes", "oss": True},
            {"name": "Dify", "domain": "dify.ai", "free": True, "icon": "", "use": "Open LLM app platform", "oss": True},
            {"name": "Flowise", "domain": "flowiseai.com", "free": True, "icon": "", "use": "Drag-drop agent builder", "oss": True},
        ],
    },
    {
        "slug": "ideas",
        "name": "Ideas",
        "kind": "Problems worth building — from real companies only",
        "tools": [
            {"name": "YC Requests", "domain": "ycombinator.com", "free": False, "icon": "ycombinator", "use": "Ideas YC wants built", "href": "https://www.ycombinator.com/rfs"},
            {"name": "Fix My Itch", "domain": "razorpay.com", "free": False, "icon": "razorpay", "use": "Real problems, India fintech", "href": "https://razorpay.com/m/fix-my-itch/"},
            {"name": "a16z Big Ideas", "domain": "a16z.com", "free": False, "icon": "", "use": "What a16z sees coming", "href": "https://a16z.com/big-ideas-in-tech-2025/"},
            {"name": "AI Grant", "domain": "aigrant.org", "free": False, "icon": "", "use": "Funded open AI ideas", "href": "https://aigrant.org/"},
            {"name": "Smart India Hackathon", "domain": "sih.gov.in", "free": False, "icon": "", "use": "Govt problem statements", "href": "https://www.sih.gov.in/"},
            {"name": "AIM Challenges", "domain": "aim.gov.in", "free": False, "icon": "", "use": "Atal innovation missions", "href": "https://aim.gov.in/"},
        ],
    },
    {
        "slug": "programs",
        "name": "Startup programs",
        "kind": "Free credits and perks for founders",
        "tools": [
            {"name": "AWS Activate", "domain": "aws.amazon.com", "free": True, "icon": "", "use": "AWS cloud credits", "href": "https://aws.amazon.com/startups"},
            {"name": "Google for Startups", "domain": "cloud.google.com", "free": True, "icon": "googlecloud", "use": "GCP credits + Workspace", "href": "https://cloud.google.com/startup/apply"},
            {"name": "NVIDIA Inception", "domain": "nvidia.com", "free": True, "icon": "nvidia", "use": "Path to $100K AWS credits", "href": "https://www.nvidia.com/en-in/startups/"},
            {"name": "MongoDB for Startups", "domain": "mongodb.com", "free": True, "icon": "mongodb", "use": "Atlas credits + advisor", "href": "https://www.mongodb.com/startups"},
            {"name": "Claude for Startups", "domain": "anthropic.com", "free": True, "icon": "claude", "use": "Claude API credits", "href": "https://www.anthropic.com/startups"},
            {"name": "OpenAI Startups", "domain": "openai.com", "free": True, "icon": "openai", "use": "Builder community + credits", "href": "https://openai.com/startups"},
            {"name": "ElevenLabs Grants", "domain": "elevenlabs.io", "free": True, "icon": "elevenlabs", "use": "Voice API grant", "href": "https://elevenlabs.io/startup-grants"},
            {"name": "Sentry for Startups", "domain": "sentry.io", "free": True, "icon": "sentry", "use": "$5K monitoring credits", "href": "https://sentry.io/for/startups/"},
            {"name": "Cloudflare Startups", "domain": "cloudflare.com", "free": True, "icon": "cloudflare", "use": "Product credits", "href": "https://www.cloudflare.com/forstartups/"},
            {"name": "GitLab for Startups", "domain": "gitlab.com", "free": True, "icon": "gitlab", "use": "Free GitLab Ultimate", "href": "https://about.gitlab.com/solutions/startups/"},
            {"name": "Retool for Startups", "domain": "retool.com", "free": True, "icon": "", "use": "Internal-tool credits", "href": "https://retool.com/startups"},
            {"name": "Persona Startups", "domain": "withpersona.com", "free": True, "icon": "", "use": "KYC + KYB free tier", "href": "https://help.withpersona.com/articles/1XNnqukfZY9VamF2e7jkuJ/"},
            {"name": "Signzy Startups", "domain": "signzy.com", "free": True, "icon": "", "use": "KYC + KYB APIs, India", "href": "https://www.signzy.com/fintech-apis/startups"},
            {"name": "AssemblyAI Startups", "domain": "assemblyai.com", "free": True, "icon": "assemblyai", "use": "Speech-to-text credits", "href": "https://www.assemblyai.com/contact/startup-program"},
            {"name": "Arize for Startups", "domain": "arize.com", "free": True, "icon": "", "use": "LLM observability + evals", "href": "https://arize.com/arize-for-startups/"},
            {"name": "Perplexity Startups", "domain": "perplexity.ai", "free": True, "icon": "perplexity", "use": "API credits + Pro", "href": "https://www.perplexity.ai/startups"},
            {"name": "DocSend Startups", "domain": "dropbox.com", "free": True, "icon": "dropbox", "use": "90% off deck sharing", "href": "https://experience.dropbox.com/docsend/startups"},
            {"name": "Infobip Tribe", "domain": "infobip.com", "free": True, "icon": "infobip", "use": "Messaging credits", "href": "https://www.infobip.com/startup-tribe"},
            {"name": "Google Ads credit", "domain": "ads.google.com", "free": True, "icon": "googleads", "use": "Ad credit after first spend", "href": "https://ads.google.com/aw/signup"},
            {"name": "Stripe Atlas", "domain": "stripe.com", "free": False, "icon": "stripe", "use": "US inc + partner perks", "href": "https://stripe.com/atlas"},
            {"name": "Azure for Students", "domain": "azure.microsoft.com", "free": True, "icon": "", "use": "$100 Azure credit", "href": "https://azure.microsoft.com/free/students"},
        ],
    },
    {
        "slug": "stack",
        "name": "Builder stack",
        "kind": "What we actually build with",
        "tools": [
            {"name": "GitHub", "domain": "github.com", "free": True, "icon": "github", "use": "Code hosting",
             "alts": [("Gitea", "about.gitea.com", "Lightweight self-host git"), ("Forgejo", "forgejo.org", "Community Gitea fork"), ("GitLab CE", "gitlab.com", "Open-core DevOps")]},
            {"name": "Supabase", "domain": "supabase.com", "free": True, "icon": "supabase", "use": "Postgres backend", "oss": True,
             "alts": [("Appwrite", "appwrite.io", "Open backend platform"), ("PocketBase", "pocketbase.io", "One-file backend"), ("Nhost", "nhost.io", "GraphQL backend")]},
            {"name": "Postman", "domain": "postman.com", "free": True, "icon": "postman", "use": "API testing",
             "alts": [("Bruno", "usebruno.com", "Offline API client"), ("Hoppscotch", "hoppscotch.io", "Web API client")]},
            {"name": "Expo", "domain": "expo.dev", "free": True, "icon": "expo", "use": "React Native builds", "oss": True},
            {"name": "Replit", "domain": "replit.com", "free": True, "icon": "replit", "use": "Cloud IDE + hosting",
             "alts": [("code-server", "coder.com", "VS Code in your browser"), ("Gitpod", "gitpod.io", "Dev environments")]},
            {"name": "Bubble", "domain": "bubble.io", "free": True, "icon": "", "use": "No-code web apps",
             "alts": [("Budibase", "budibase.com", "Open low-code apps"), ("Appsmith", "appsmith.com", "Open internal tools"), ("ToolJet", "tooljet.com", "Open app builder")]},
            {"name": "PostHog", "domain": "posthog.com", "free": True, "icon": "posthog", "use": "Product analytics", "oss": True,
             "alts": [("Umami", "umami.is", "Simple web analytics"), ("Matomo", "matomo.org", "Full analytics suite"), ("Plausible", "plausible.io", "Privacy-first analytics")]},
            {"name": "Resend", "domain": "resend.com", "free": True, "icon": "resend", "use": "Email API",
             "alts": [("Postal", "postalserver.io", "Self-hosted mail server"), ("Listmonk", "listmonk.app", "Newsletter + campaigns")]},
            {"name": "New Relic", "domain": "newrelic.com", "free": True, "icon": "newrelic", "use": "App monitoring",
             "alts": [("SigNoz", "signoz.io", "Open observability"), ("Grafana", "grafana.com", "Dashboards + traces"), ("OpenObserve", "openobserve.ai", "Logs at 140x less cost")]},
            {"name": "CodeRabbit", "domain": "coderabbit.ai", "free": True, "icon": "", "use": "AI pull-request reviews",
             "alts": [("PR-Agent", "github.com", "Qodo's open PR reviewer")]},
            {"name": "Notion", "domain": "notion.so", "free": True, "icon": "notion", "use": "Docs and wikis",
             "alts": [("AppFlowy", "appflowy.io", "Open Notion alternative"), ("AFFiNE", "affine.pro", "Docs + whiteboard"), ("Outline", "getoutline.com", "Team knowledge base")]},
            {"name": "Slack", "domain": "slack.com", "free": True, "icon": "slack", "use": "Team chat",
             "alts": [("Mattermost", "mattermost.com", "Self-hosted team chat"), ("Rocket.Chat", "rocket.chat", "Open team chat"), ("Zulip", "zulip.com", "Threaded open chat")]},
            {"name": "Whimsical", "domain": "whimsical.com", "free": True, "icon": "", "use": "Diagrams and wireframes",
             "alts": [("Excalidraw", "excalidraw.com", "Hand-drawn diagrams"), ("tldraw", "tldraw.com", "Infinite canvas"), ("draw.io", "drawio.com", "Classic diagramming")]},
            {"name": "Google AI Studio", "domain": "aistudio.google.com", "free": True, "icon": "", "use": "Gemini API playground",
             "alts": [("Open WebUI", "openwebui.com", "Self-hosted chat UI")]},
            {"name": "Otter", "domain": "otter.ai", "free": True, "icon": "", "use": "Meeting notes",
             "alts": [("Whisper", "github.com", "OpenAI's open STT")]},
            {"name": "Mercury", "domain": "mercury.com", "free": True, "icon": "", "use": "Startup banking"},
            {"name": "LaunchDarkly", "domain": "launchdarkly.com", "free": False, "icon": "launchdarkly", "use": "Feature flags",
             "alts": [("Unleash", "getunleash.io", "Open feature flags"), ("Flagsmith", "flagsmith.com", "Flags + remote config"), ("GrowthBook", "growthbook.io", "Flags + A/B tests")]},
            {"name": "Razorpay", "domain": "razorpay.com", "free": False, "icon": "razorpay", "use": "Indian payments"},
        ],
    },
]
